name: master CI, CD workflow 
on: 
  push:
    branches: [ "Okteto"]
  pull_request:
    branches: [ "Okteto"]
jobs:
  master-ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Read .env file
        id: env
        run: |
          cat ../../.env
          while read -r line || [[ -n "$line" ]]; do
            # Split each line into variable name and value
            var_name=$(echo "$line" | cut -d'=' -f1)
            var_value=$(echo "$line" | cut -d'=' -f2-)
            # Set the variable in the environment
            echo "##[set-env name=$var_name;]$var_value"
          done < ../../.env

      - name: Show env values
        run: |
          echo "DATABASE_URL_LOCAL=$DATABASE_URL_LOCAL"
          echo "DATABASE_URL_NEON=$DATABASE_URL_NEON"
          echo "type=$type"
          echo "project_id=$project_id"
          echo "private_key_id=$private_key_id"
          echo "private_key=$private_key"
          echo "client_email=$client_email"
          echo "client_id=$client_id"
          echo "auth_uri=$auth_uri"
          echo "token_uri=$token_uri"
          echo "auth_provider_x509_cert_url=$auth_provider_x509_cert_url"
          echo "client_x509_cert_url=$client_x509_cert_url"
          echo "universe_domain=$universe_domain"
          echo "postgres_Titulo=$postgres_Titulo"
          echo "postgres_Usuario=$postgres_Usuario"
          echo "postgres_Contrasena=$postgres_Contrasena"
          echo "postgres_Host=$postgres_Host"
      
      - name: show dir, .env file
        run: |
          cat .env 
          
      - name: Build the custom Docker image
        run: docker build -t ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.sha}} .

      - name: show docker images
        run: docker images

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
          
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.sha}}
      
      - name: update docker user in k8 
        run: sed -i 's/{docker_user}/${{secrets.DOCKER_USER}}/g' manifests/k8s.yml

      - name: update model name in k8 
        run: sed -i 's/{model_name}/${{secrets.MODEL_NAME}}/g' manifests/k8s.yml

      - name: update _ by - 
        run: sed -i 's/_/-/g' manifests/k8s.yml

      - name: update sha in k8
        run: sed -i 's/{github.sha}/${{github.sha}}/g' manifests/k8s.yml

      - name: ls -la 
        run: cat manifests/k8s.yml
        
      - uses: okteto/context@2.7.0
        with:
          token: ${{secrets.OKTETO_TOKEN }}

      - name: Deploy and Wait
        uses: okteto/actions/deploy@v1
        env:
          KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
        with:
          namespace: ${{secrets.OKTETO_NAMESPACE }}
          manifest: manifests/k8s.yml
          tag: ${{ secrets.DOCKER_USERNAME }}/${{secrets.MODEL_NAME}}:${{github.sha}}
