name: master CI, CD workflow 
on: 
  push:
    branches: [ "Okteto"]
  pull_request:
    branches: [ "Okteto"]
jobs:
  master-ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Create .env file
        run: |
          echo "DATABASE_URL_LOCAL=${{ secrets.DATABASE_URL_LOCAL }}" > .env
          echo "DATABASE_URL_NEON=${{ secrets.DATABASE_URL_NEON }}" >> .env
          echo "type=${{ secrets.type }}" >> .env
          echo "project_id=${{ secrets.project_id }}" >> .env
          echo "private_key_id=${{ secrets.private_key_id }}" >> .env
          echo "private_key=-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCmbKsswaLueXJu\nkjA+RWNqFUz2nyZ8QcQX7B5pl8x8TDOi4ks0hHAsGvKSg3yGLQoFSrrzuhx5ha4f\nwU/50njUz9qm4bHrhMBEh7zGbfvmyN0Ans9WqSwZqZEvf5GdHJw6XqfuA9vUrfOp\nIOkSmjZYwXrKFRbk5u6HglpGrJKBVzRXXkHTd7R4z4gNLj8TAke3lokBJCVsN5A8\nodS62JC9Sp6B4BR0jwDP8Q6pKAhEOtlj2j8/ADvJI0xKQSdmJ5rGwki/yeEZYNop\nCt/YbjfNQWqKSnd8S2cuTxcY8uYV4naEc2KZemaPcoYLINvvQX6hO5Dje9PsJldI\n1nWKUBYLAgMBAAECggEAOlN+gG6SxEJTDRZ2CvT1nRG/CfYIHmdMKtgpZnd5hpyM\nQktN8SdzSrndBuVHKJ0zVFx2/gFdhmeH+YAeH9+YUnlQV8lkujapzbrGucKFFMKT\n1epSnzwmBQ5tIDj01xvWUwymjR/UFQssCLvMg6UBZATXHGjcv7eBpINWUUudAu/0\n50fbEXW7X3mek1E9H2TZj3U3/oveQb/Uw+VOVu3sJVn+JOuNmsP1WeVZCYH6z9uI\nfILpk3vdO80CHcjp5CwbpwNIN9MlV891CG7hR0y/x9aqPydI5khKrk9509YpIVae\n+/LUFKUqBtPgCLlFx/PDIcJX63PPBSloUxvlrGxUtQKBgQDSK7Z4sUGHnJSCk6i3\neqaPiXRBHV+1yYXCwl7NyUwvRcO9f43dTz0l87um/B/BHIEa+ApgPvvuOT16pk64\nLHWPKmuf4zOA9IE0T3g+c0YFhGDSzHoXxEN2l6j8+KoUM5fKCSaV4DbhYvKrTkki\nFTyqiKJs19gZXZOqTkndNUUY5wKBgQDKtuxx4xzK8tWInZ54Beu6XICioSU7rEdj\nkCPZmDq4jmyWFrF7pjanDRBGGeGMdJOu2aBKBEOUjBa6JzWm+DnEu91nKYLOst8/\nlANwdTwAXiCQAiRvJjtjhZPTv6mame5W1Oy2WVdUbDFP7wAfntn3fp11MD1Pq4Tm\nVwGBNPXBPQKBgQClp97DcrN7+Gb2JPyu4fW23VjMmiJ+XsEXqayf9zIdcJfAHXHs\nJjDEYUBfdgpxY84/O5KyGfLo6iUTL1KMyD5BAeait6o40n+kg577WlCuuJC4loMF\niKTELPX9ruIf2iqiDGRlbbzUGfG8JJBwVNzkbZ3YvKiQFbn2Wo7N1NcJsQKBgQCv\nNqjsT0ely3rx2HsOdt+ndyjgaLTL/T6/OekivMeUmdYVbIv/ukzm2w3D6b7gLisw\nKH65OzJGhUdno1hmd4tHFrJp5qFfk5APXhoS6+Hu120BzDg9sigG/4AkuDcaoA44\nE1Z+zn4DRHjjBEtxCVaQ62mhzw5PfIskpPNyAJqiaQKBgBDVVOJWQO4gH5ExZPqd\n54Zi7d5a7sQNpubo7iX4eDZ4gg59sT4vV/a6T84MIjZ4S5tjEnM9NWaH9ZV2FWRD\ncYv5Cc5w8VfI2rtUKM+svs8iwglpGIHsaRIPXylC6h13Fv53+lLYW47g+S3HjKyr\nnsPzbS1p1FTtWv/edLS2j+Hy\n-----END PRIVATE KEY-----" >> .env
          echo "client_email=${{ secrets.client_email }}" >> .env
          echo "client_id=${{ secrets.client_id }}" >> .env
          echo "auth_uri=${{ secrets.auth_uri }}" >> .env
          echo "token_uri=${{ secrets.token_uri }}" >> .env
          echo "auth_provider_x509_cert_url=${{ secrets.auth_provider_x509_cert_url }}" >> .env
          echo "client_x509_cert_url=${{ secrets.client_x509_cert_url }}" >> .env
          echo "universe_domain=${{ secrets.universe_domain }}" >> .env
          echo "postgres_Titulo=${{ secrets.postgres_Titulo }}" >> .env
          echo "postgres_Usuario=${{ secrets.postgres_Usuario }}" >> .env
          echo "postgres_Contrasena=${{ secrets.postgres_Contrasena }}" >> .env
          echo "postgres_Host=${{ secrets.postgres_Host }}" >> .env
        shell: bash
      
      - name: show dir, .env file
        run: |
          cat .env 
          
      - name: Build the custom Docker image
        run: docker build -t ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.sha}} .

      - name: show docker images
        run: docker images

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
          
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.sha}}
      
      - name: update docker user in k8 
        run: sed -i 's/{docker_user}/${{secrets.DOCKER_USER}}/g' manifests/k8s.yml

      - name: update model name in k8 
        run: sed -i 's/{model_name}/${{secrets.MODEL_NAME}}/g' manifests/k8s.yml

      - name: update _ by - 
        run: sed -i 's/_/-/g' manifests/k8s.yml

      - name: update sha in k8
        run: sed -i 's/{github.sha}/${{github.sha}}/g' manifests/k8s.yml

      - name: ls -la 
        run: cat manifests/k8s.yml
        
      - uses: okteto/context@2.7.0
        with:
          token: ${{secrets.OKTETO_TOKEN }}

      - name: Deploy and Wait
        uses: okteto/actions/deploy@v1
        env:
          KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
        with:
          namespace: ${{secrets.OKTETO_NAMESPACE }}
          manifest: manifests/k8s.yml
          tag: ${{ secrets.DOCKER_USERNAME }}/${{secrets.MODEL_NAME}}:${{github.sha}}
